export const promoData = [
  {
    id: '1',
    badge: '🔥 MEGA MALL SALE',
    discount: 'UP TO 60% OFF',
    title: 'On Fresh Dairy, Fruits, Snacks & Staples',
    buttonText: 'SHOP DEALS NOW →',
    bgGradient: ['#064E3B', '#047857'],
    accentColor: '#FACC15',
    image: require('../../../../assets/grocery-banner.png'),
  },
  {
    id: '2',
    badge: '⚡ BUY 1 GET 1 FREE',
    discount: 'BOGO SUPER DEALS',
    title: 'On Select Chocolates, Beverages & Frozen Meals',
    buttonText: 'GRAB OFFER NOW →',
    bgGradient: ['#9A3412', '#C2410C'],
    accentColor: '#FEF08A',
    image: require('../../../../assets/grocery-banner.png'),
  },
  {
    id: '3',
    badge: '🎉 WEEKEND SPECIAL',
    discount: 'FLAT ₹150 OFF',
    title: 'Use Code: GROMALL150 on Orders Above ₹500',
    buttonText: 'CLAIM COUPON →',
    bgGradient: ['#1E1B4B', '#3730A3'],
    accentColor: '#38BDF8',
    image: require('../../../../assets/grocery-banner.png'),
  },
];
